# Generated by Django 5.2 on 2025-12-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tag_alter_post_options_post_is_active_post_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='tags/%Y/%m/%d'),
        ),
    ]
