# Generated by Django 5.2 on 2025-12-28 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_likes_count_comment_replays_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='replay',
            index=models.Index(fields=['-likes_count', '-created_at'], name='replays_likes_c_9f2633_idx'),
        ),
    ]
