# Generated by Django 5.2 on 2025-12-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_replay_likes_count_replay_replays_likes_c_9f2633_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replay',
            options={'ordering': ['-created_at'], 'verbose_name': 'Replay', 'verbose_name_plural': 'Replays'},
        ),
    ]
