# Generated by Django 6.0.2 on 2026-02-11 18:15

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_comment_post_alter_comment_user_alter_post_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='posts/%Y/%m/%d'),
        ),
    ]
