# Generated by Django 5.2 on 2025-12-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_tag_slug_alter_tag_id_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
