# Generated by Django 5.2 on 2025-12-27 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_tag_options_tag_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='posts.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Replay',
                'verbose_name_plural': 'Replays',
                'db_table': 'replays',
                'indexes': [models.Index(fields=['comment', '-created_at'], name='replays_comment_7c7113_idx')],
            },
        ),
    ]
