# Generated by Django 6.0.2 on 2026-02-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='developer',
            field=models.CharField(max_length=255, unique=True, verbose_name='Developer'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='production_enabled',
            field=models.BooleanField(default=False, verbose_name='Production Enabled'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='staging_enabled',
            field=models.BooleanField(default=False, verbose_name='Staging Enabled'),
        ),
    ]
