# Generated by Django 6.0.2 on 2026-02-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_feature_created_at_alter_feature_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='developer',
            field=models.CharField(max_length=255, verbose_name='Developer'),
        ),
    ]
