# Generated by Django 6.0.2 on 2026-02-16 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessages',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='rtchats.chatgroup'),
        ),
    ]
