# Generated by Django 6.0.2 on 2026-02-16 15:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtchats', '0002_alter_groupmessages_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMessages',
            new_name='GroupMessage',
        ),
    ]
