# Generated by Django 6.0.2 on 2026-02-21 16:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchats', '0005_chatgroup_is_private_chatgroup_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=uuid.uuid4, max_length=128, unique=True),
        ),
    ]
